// frontend/src/pages/Dashboard.vue
<template>
  <div class="dashboard">
    <div class="header">
      <h1>仪表盘</h1>
      <el-button type="primary" @click="handleSync" :loading="syncing">
        <el-icon><Refresh /></el-icon>
        同步邮件
      </el-button>
    </div>

    <el-row :gutter="20" class="stats-grid">
      <el-col :span="6">
        <el-card shadow="hover">
          <div class="stat-card">
            <div class="stat-value">{{ emailStore.total }}</div>
            <div class="stat-label">总邮件数</div>
          </div>
        </el-card>
      </el-col>
      <el-col :span="6">
        <el-card shadow="hover">
          <div class="stat-card">
            <div class="stat-value">{{ eventStore.events.length }}</div>
            <div class="stat-label">提取事件数</div>
          </div>
        </el-card>
      </el-col>
      <el-col :span="6">
        <el-card shadow="hover">
          <div class="stat-card">
            <div class="stat-value">{{ eventStore.importantEvents.length }}</div>
            <div class="stat-label">重要事件</div>
          </div>
        </el-card>
      </el-col>
      <el-col :span="6">
        <el-card shadow="hover">
          <div class="stat-card">
            <div class="stat-value">{{ pendingCount }}</div>
            <div class="stat-label">待处理</div>
          </div>
        </el-card>
      </el-col>
    </el-row>

    <el-card class="recent-events">
      <template #header>
        <div class="card-header">
          <span>最近事件</span>
          <el-button type="primary" link @click="$router.push('/timeline')">查看全部</el-button>
        </div>
      </template>
      <el-table :data="recentEvents" style="width: 100%" v-loading="loading">
        <el-table-column prop="event_type" label="类型" width="100">
          <template #default="{ row }">
            <el-tag :type="getTypeColor(row.event_type)">{{ row.event_type }}</el-tag>
          </template>
        </el-table-column>
        <el-table-column prop="title" label="标题" />
        <el-table-column prop="event_time" label="时间" width="180">
          <template #default="{ row }">
            {{ row.event_time ? formatDate(row.event_time) : '-' }}
          </template>
        </el-table-column>
        <el-table-column prop="important" label="重要" width="80">
          <template #default="{ row }">
            <el-icon v-if="row.important" color="#F59E0B"><Star /></el-icon>
          </template>
        </el-table-column>
        <el-table-column label="操作" width="80">
          <template #default="{ row }">
            <el-button type="primary" link @click="viewEvent(row)">详情</el-button>
          </template>
        </el-table-column>
      </el-table>
      <el-empty v-if="!recentEvents.length && !loading" description="暂无事件" />
    </el-card>

    <el-dialog v-model="detailVisible" title="事件详情" width="500px">
      <el-descriptions v-if="currentEvent" :column="1" border>
        <el-descriptions-item label="类型">
          <el-tag :type="getTypeColor(currentEvent.event_type)">{{ currentEvent.event_type }}</el-tag>
        </el-descriptions-item>
        <el-descriptions-item label="标题">{{ currentEvent.title }}</el-descriptions-item>
        <el-descriptions-item label="时间">
          {{ currentEvent.event_time ? formatDate(currentEvent.event_time) : '-' }}
        </el-descriptions-item>
        <el-descriptions-item label="地点">{{ currentEvent.location || '-' }}</el-descriptions-item>
      </el-descriptions>
      <template #footer>
        <el-button @click="detailVisible = false">关闭</el-button>
      </template>
    </el-dialog>
  </div>
</template>

<script setup lang="ts">
import { ref, computed, onMounted } from 'vue'
import { ElMessage } from 'element-plus'
import { Refresh, Star } from '@element-plus/icons-vue'
import { useEmailStore } from '@/stores/email'
import { useEventStore } from '@/stores/event'
import { emailApi } from '@/api/emails'
import type { Event } from '@/api/types'

const emailStore = useEmailStore()
const eventStore = useEventStore()
const syncing = ref(false)
const loading = ref(false)
const detailVisible = ref(false)
const currentEvent = ref<Event | null>(null)

const recentEvents = computed(() => eventStore.events.slice(0, 5))

const pendingCount = computed(() => {
  return emailStore.emails.filter(e => !e.processed).length
})

function getTypeColor(type: string): string {
  if (!type) return 'info'
  const PALETTE = ['', 'success', 'warning', 'danger', 'info', 'primary']
  let hash = 0
  for (let i = 0; i < type.length; i++) hash += type.charCodeAt(i)
  return PALETTE[Math.abs(hash) % PALETTE.length]
}

function formatDate(date: string) {
  return new Date(date).toLocaleString('zh-CN')
}

function viewEvent(event: Event) {
  currentEvent.value = event
  detailVisible.value = true
}

async function handleSync() {
  syncing.value = true
  try {
    const result = await emailApi.sync({ days: 7, limit: 100 })
    if (result?.success) {
      ElMessage.success(`同步成功: ${result.synced}封`)
      await loadData()
    } else {
      ElMessage.error('同步失败')
    }
  } catch {
    ElMessage.error('同步失败')
  } finally {
    syncing.value = false
  }
}

async function loadData() {
  loading.value = true
  try {
    await Promise.all([
      emailStore.fetchEmails({ limit: 1000 }),
      eventStore.fetchEvents({ limit: 1000 })
    ])
  } finally {
    loading.value = false
  }
}

onMounted(() => {
  loadData()
})
</script>

<style scoped>
.dashboard {
  padding: 24px;
}

.header {
  display: flex;
  justify-content: space-between;
  align-items: center;
  margin-bottom: 24px;
}

.header h1 {
  font-size: 24px;
  font-weight: 600;
}

.stats-grid {
  margin-bottom: 24px;
}

.stat-card {
  text-align: center;
  padding: 12px;
}

.stat-value {
  font-size: 32px;
  font-weight: 700;
  color: #4F46E5;
}

.stat-label {
  font-size: 14px;
  color: #6B7280;
  margin-top: 4px;
}

.recent-events {
  margin-top: 24px;
}

.card-header {
  display: flex;
  justify-content: space-between;
  align-items: center;
  font-size: 16px;
  font-weight: 600;
}
</style>

// frontend/src/pages/Dashboard.tsx
import { useEffect, useState } from 'react'
import { Row, Col, Card, Statistic, Table, Button, Tag, Modal, Descriptions, message } from 'antd'
import { ReloadOutlined, StarOutlined } from '@ant-design/icons'
import { useEmailStore } from '@/stores/email'
import { useEventStore } from '@/stores/event'
import { emailApi } from '@/api/emails'
import type { Event } from '@/api/types'

const TYPE_PALETTE = ['', 'success', 'warning', 'danger', 'info', 'primary']

function getTypeColor(type: string): string {
  if (!type) return 'info'
  let hash = 0
  for (let i = 0; i < type.length; i++) hash += type.charCodeAt(i)
  return TYPE_PALETTE[Math.abs(hash) % TYPE_PALETTE.length]
}

function formatDate(date: string) {
  return new Date(date).toLocaleString('zh-CN')
}

export default function Dashboard() {
  const { emails, fetchEmails } = useEmailStore()
  const { events, fetchEvents } = useEventStore()
  const [syncing, setSyncing] = useState(false)
  const [loading, setLoading] = useState(false)
  const [detailVisible, setDetailVisible] = useState(false)
  const [currentEvent, setCurrentEvent] = useState<Event | null>(null)

  const recentEvents = events.slice(0, 5)
  const pendingCount = emails.filter((email) => !email.processed).length

  async function loadData() {
    setLoading(true)
    try {
      await Promise.all([fetchEmails({ limit: 1000 }), fetchEvents({ limit: 1000 })])
    } finally {
      setLoading(false)
    }
  }

  async function handleSync() {
    setSyncing(true)
    try {
      const result = await emailApi.sync({ days: 7, limit: 100 })
      if (result.success) {
        message.success(`同步成功：新增 ${result.synced} 封邮件`)
      } else {
        message.error('同步失败')
      }
      await loadData()
    } catch {
      message.error('同步失败')
    } finally {
      setSyncing(false)
    }
  }

  function viewEvent(event: Event) {
    setCurrentEvent(event)
    setDetailVisible(true)
  }

  useEffect(() => {
    async function initialize() {
      setLoading(true)
      try {
        await Promise.all([fetchEmails({ limit: 1000 }), fetchEvents({ limit: 1000 })])
      } finally {
        setLoading(false)
      }
    }

    void initialize()
  }, [fetchEmails, fetchEvents])

  const eventColumns = [
    {
      title: '类型',
      dataIndex: 'event_type',
      key: 'event_type',
      width: 100,
      render: (type: string) => <Tag color={getTypeColor(type)}>{type || '未分类'}</Tag>,
    },
    { title: '标题', dataIndex: 'title', key: 'title' },
    {
      title: '时间',
      dataIndex: 'event_time',
      key: 'event_time',
      width: 180,
      render: (time: string) => (time ? formatDate(time) : '-'),
    },
    {
      title: '重要',
      dataIndex: 'important',
      key: 'important',
      width: 80,
      render: (important: boolean) => (important ? <StarOutlined style={{ color: '#F59E0B' }} /> : null),
    },
    {
      title: '操作',
      key: 'action',
      width: 80,
      render: (_: unknown, record: Event) => (
        <Button type="link" onClick={() => viewEvent(record)}>
          详情
        </Button>
      ),
    },
  ]

  return (
    <div style={{ padding: 24 }}>
      <div
        style={{
          display: 'flex',
          justifyContent: 'space-between',
          alignItems: 'center',
          marginBottom: 24,
        }}
      >
        <h1 style={{ fontSize: 24, fontWeight: 600, margin: 0 }}>仪表盘</h1>
        <Button type="primary" icon={<ReloadOutlined />} loading={syncing} onClick={handleSync}>
          同步邮件
        </Button>
      </div>

      <Row gutter={20} style={{ marginBottom: 24 }}>
        <Col span={6}>
          <Card hoverable>
            <Statistic title="邮件总数" value={emails.length} />
          </Card>
        </Col>
        <Col span={6}>
          <Card hoverable>
            <Statistic title="提取事件数" value={events.length} />
          </Card>
        </Col>
        <Col span={6}>
          <Card hoverable>
            <Statistic title="重要事件" value={events.filter((event) => event.important).length} />
          </Card>
        </Col>
        <Col span={6}>
          <Card hoverable>
            <Statistic title="待处理邮件" value={pendingCount} />
          </Card>
        </Col>
      </Row>

      <Card
        title="最近事件"
        extra={(
          <Button type="link" onClick={() => { window.location.hash = '#/timeline' }}>
            查看全部
          </Button>
        )}
      >
        <Table
          dataSource={recentEvents}
          columns={eventColumns}
          rowKey="id"
          loading={loading}
          pagination={false}
          locale={{ emptyText: '暂无事件' }}
        />
      </Card>

      <Modal
        title="事件详情"
        open={detailVisible}
        onCancel={() => setDetailVisible(false)}
        footer={<Button onClick={() => setDetailVisible(false)}>关闭</Button>}
      >
        {currentEvent && (
          <Descriptions column={1} bordered>
            <Descriptions.Item label="类型">
              <Tag color={getTypeColor(currentEvent.event_type)}>{currentEvent.event_type || '未分类'}</Tag>
            </Descriptions.Item>
            <Descriptions.Item label="标题">{currentEvent.title}</Descriptions.Item>
            <Descriptions.Item label="时间">
              {currentEvent.event_time ? formatDate(currentEvent.event_time) : '-'}
            </Descriptions.Item>
            <Descriptions.Item label="地点">{currentEvent.location || '-'}</Descriptions.Item>
            <Descriptions.Item label="状态">{currentEvent.status || '-'}</Descriptions.Item>
          </Descriptions>
        )}
      </Modal>
    </div>
  )
}
