// frontend/src/pages/Settings.tsx
import { useEffect, useState } from 'react'
import { Button, Card, Form, Input, InputNumber, Result, Space, Table, Tag, message } from 'antd'
import { CheckCircleOutlined, FileTextOutlined, MailOutlined, ReloadOutlined } from '@ant-design/icons'

import { systemApi } from '@/api/system'
import type { Job } from '@/api/types'

const TAG_TYPES = ['', 'success', 'warning', 'danger', 'info', 'primary', 'success', 'warning']

function getTypeColor(index: number): string {
  return TAG_TYPES[index % TAG_TYPES.length]
}

interface TestResult {
  success: boolean
  message: string
}

export default function Settings() {
  const [form] = Form.useForm()
  const [categories, setCategories] = useState<string[]>([])
  const [inputVisible, setInputVisible] = useState(false)
  const [inputValue, setInputValue] = useState('')
  const [saving, setSaving] = useState(false)
  const [testing, setTesting] = useState(false)
  const [testResult, setTestResult] = useState<TestResult | null>(null)
  const [syncing, setSyncing] = useState(false)
  const [parsing, setParsing] = useState(false)
  const [sending, setSending] = useState(false)
  const [jobs, setJobs] = useState<Job[]>([])
  const [jobsLoading, setJobsLoading] = useState(false)

  async function saveSettings() {
    setSaving(true)
    try {
      const values = form.getFieldsValue()
      await systemApi.updateSettings({
        check_interval: values.check_interval,
        scheduled_send_hour: values.scheduled_send_hour,
        scheduled_send_minute: values.scheduled_send_minute,
        categories,
      })
      message.success('设置已保存')
      await loadJobs()
    } catch {
      message.error('保存设置失败')
    } finally {
      setSaving(false)
    }
  }

  async function testConnection() {
    setTesting(true)
    setTestResult(null)
    try {
      const result = await systemApi.testConnection()
      setTestResult({ success: true, message: result.message || '连接成功' })
    } catch (error: unknown) {
      const err = error as { detail?: string }
      setTestResult({ success: false, message: err.detail || '连接失败' })
    } finally {
      setTesting(false)
    }
  }

  async function handleSync() {
    setSyncing(true)
    try {
      const result = await systemApi.triggerSync()
      if (result.success) {
        message.success(`同步完成：新增 ${result.synced} 封邮件`)
      } else {
        message.error('同步失败')
      }
    } catch {
      message.error('同步失败')
    } finally {
      setSyncing(false)
    }
  }

  async function handleParse() {
    setParsing(true)
    try {
      const result = await systemApi.triggerParse()
      message.success(`解析完成：${result.processed} 封邮件`)
    } catch {
      message.error('解析失败')
    } finally {
      setParsing(false)
    }
  }

  async function sendSummary() {
    setSending(true)
    try {
      await systemApi.sendDailySummary()
      message.success('测试摘要已发送')
    } catch {
      message.error('发送测试摘要失败')
    } finally {
      setSending(false)
    }
  }

  async function loadJobs() {
    setJobsLoading(true)
    try {
      const data = await systemApi.getJobs()
      setJobs(Array.isArray(data) ? data : [])
    } catch {
      setJobs([])
    } finally {
      setJobsLoading(false)
    }
  }

  function removeCategory(category: string) {
    setCategories((prev) => prev.filter((item) => item !== category))
  }

  function handleInputConfirm() {
    const nextValue = inputValue.trim()
    if (nextValue) {
      setCategories((prev) => [...prev, nextValue])
    }
    setInputVisible(false)
    setInputValue('')
  }

  useEffect(() => {
    async function initialize() {
      try {
        const data = await systemApi.getSettings()
        form.setFieldsValue({
          check_interval: data.check_interval,
          scheduled_send_hour: data.scheduled_send_hour,
          scheduled_send_minute: data.scheduled_send_minute,
        })
        setCategories(data.categories || [])
      } catch (error) {
        console.error('Failed to load settings', error)
      }

      await loadJobs()
    }

    void initialize()
  }, [form])

  return (
    <div style={{ padding: 24 }}>
      <h1 style={{ fontSize: 24, fontWeight: 600, marginBottom: 24 }}>设置</h1>

      <Card style={{ marginBottom: 20 }}>
        <h3 style={{ marginBottom: 16 }}>同步设置</h3>
        <Form form={form} layout="vertical">
          <Form.Item label="检查间隔" name="check_interval">
            <InputNumber min={1} max={60} addonAfter="分钟" />
          </Form.Item>
          <Form.Item label="每日摘要时间">
            <Space>
              <Form.Item name="scheduled_send_hour" noStyle>
                <InputNumber min={0} max={23} placeholder="小时" />
              </Form.Item>
              <Form.Item name="scheduled_send_minute" noStyle>
                <InputNumber min={0} max={59} placeholder="分钟" />
              </Form.Item>
            </Space>
          </Form.Item>
          <Form.Item>
            <Button type="primary" onClick={saveSettings} loading={saving}>
              保存设置
            </Button>
          </Form.Item>
        </Form>
      </Card>

      <Card style={{ marginBottom: 20 }}>
        <h3 style={{ marginBottom: 16 }}>分类</h3>
        <div style={{ display: 'flex', flexWrap: 'wrap', gap: 8 }}>
          {categories.map((category, index) => (
            <Tag
              key={category}
              color={getTypeColor(index)}
              closable
              onClose={() => removeCategory(category)}
            >
              {category}
            </Tag>
          ))}
          {inputVisible ? (
            <Input
              value={inputValue}
              onChange={(event) => setInputValue(event.target.value)}
              onPressEnter={handleInputConfirm}
              onBlur={handleInputConfirm}
              style={{ width: 120 }}
              autoFocus
            />
          ) : (
            <Button size="small" onClick={() => setInputVisible(true)}>
              + 添加分类
            </Button>
          )}
        </div>
      </Card>

      <Card style={{ marginBottom: 20 }}>
        <h3 style={{ marginBottom: 16 }}>连接测试</h3>
        <Button icon={<CheckCircleOutlined />} onClick={testConnection} loading={testing}>
          测试 IMAP 连接
        </Button>
        {testResult && (
          <Result
            status={testResult.success ? 'success' : 'error'}
            title={testResult.message}
            style={{ marginTop: 16, padding: 0 }}
          />
        )}
      </Card>

      <Card style={{ marginBottom: 20 }}>
        <h3 style={{ marginBottom: 16 }}>手动操作</h3>
        <Space>
          <Button type="primary" icon={<ReloadOutlined />} loading={syncing} onClick={handleSync}>
            立即同步
          </Button>
          <Button icon={<FileTextOutlined />} loading={parsing} onClick={handleParse}>
            解析全部邮件
          </Button>
          <Button icon={<MailOutlined />} loading={sending} onClick={sendSummary}>
            发送测试摘要
          </Button>
        </Space>
      </Card>

      <Card title="定时任务">
        <Table
          dataSource={jobs}
          rowKey="id"
          loading={jobsLoading}
          pagination={false}
          locale={{ emptyText: '暂无定时任务' }}
          columns={[
            { title: '任务 ID', dataIndex: 'id', key: 'id' },
            { title: '任务名称', dataIndex: 'name', key: 'name' },
            { title: '下次执行时间', dataIndex: 'next_run_time', key: 'next_run_time' },
          ]}
        />
      </Card>
    </div>
  )
}

// frontend/src/pages/Settings.vue
<template>
  <div class="settings-page">
    <div class="header">
      <h1>设置</h1>
    </div>

    <el-row :gutter="20">
      <el-col :span="12">
        <el-card class="settings-card">
          <template #header>
            <div class="card-header">
              <span>同步设置</span>
            </div>
          </template>
          <el-form label-width="120px">
            <el-form-item label="邮件检查间隔">
              <el-input-number v-model="settings.check_interval" :min="1" :max="60" />
              <span class="form-tip">分钟</span>
            </el-form-item>
            <el-form-item label="定时推送时间">
              <el-time-select
                v-model="scheduledTime"
                start="00:00"
                step="00:15"
                end="23:59"
                placeholder="选择时间"
              />
            </el-form-item>
            <el-form-item>
              <el-button type="primary" @click="saveSettings" :loading="saving">
                保存设置
              </el-button>
            </el-form-item>
          </el-form>
        </el-card>
      </el-col>

      <el-col :span="12">
        <el-card class="settings-card">
          <template #header>
            <div class="card-header">
              <span>分类标签</span>
            </div>
          </template>
          <div class="categories">
            <el-tag
              v-for="(cat, index) in settings.categories"
              :key="cat"
              :type="getTypeColor(index)"
              closable
              @close="removeCategory(cat)"
            >
              {{ cat }}
            </el-tag>
            <el-input
              v-if="inputVisible"
              ref="inputRef"
              v-model="inputValue"
              class="input-new-tag"
              size="small"
              @keyup.enter="handleInputConfirm"
              @blur="handleInputConfirm"
            />
            <el-button v-else size="small" @click="showInput">+ 新建分类</el-button>
          </div>
        </el-card>
      </el-col>
    </el-row>

    <el-card class="settings-card mt-20">
      <template #header>
        <div class="card-header">
          <span>连接测试</span>
        </div>
      </template>
      <el-button @click="testConnection" :loading="testing">
        <el-icon><Connection /></el-icon>
        测试 IMAP 连接
      </el-button>
      <el-result
        v-if="testResult"
        :icon="testResult.success ? 'success' : 'error'"
        :title="testResult.message"
      />
    </el-card>

    <el-card class="settings-card mt-20">
      <template #header>
        <div class="card-header">
          <span>手动操作</span>
        </div>
      </template>
      <el-space>
        <el-button type="primary" @click="handleSync" :loading="syncing">
          <el-icon><Refresh /></el-icon>
          立即同步
        </el-button>
        <el-button @click="handleParse" :loading="parsing">
          <el-icon><Document /></el-icon>
          解析全部邮件
        </el-button>
        <el-button @click="sendSummary" :loading="sending">
          <el-icon><Message /></el-icon>
          发送测试摘要
        </el-button>
      </el-space>
    </el-card>

    <el-card class="settings-card mt-20">
      <template #header>
        <div class="card-header">
          <span>定时任务状态</span>
        </div>
      </template>
      <el-table :data="jobs" v-loading="jobsLoading">
        <el-table-column prop="id" label="任务ID" width="150" />
        <el-table-column prop="name" label="任务名称" />
        <el-table-column prop="next_run_time" label="下次执行时间" />
      </el-table>
      <el-empty v-if="!jobs.length && !jobsLoading" description="暂无定时任务" />
    </el-card>
  </div>
</template>

<script setup lang="ts">
import { ref, reactive, onMounted, nextTick } from 'vue'
import { ElMessage } from 'element-plus'
import { Connection, Refresh, Document, Message } from '@element-plus/icons-vue'
import { systemApi } from '@/api/system'

const settings = reactive({
  check_interval: 5,
  scheduled_send_hour: 9,
  scheduled_send_minute: 0,
  categories: [] as string[]
})

const scheduledTime = ref('09:00')
const saving = ref(false)
const testing = ref(false)
const testResult = ref<{ success: boolean; message: string } | null>(null)
const syncing = ref(false)
const parsing = ref(false)
const sending = ref(false)
const jobs = ref<any[]>([])
const jobsLoading = ref(false)

const inputVisible = ref(false)
const inputValue = ref('')
const inputRef = ref<HTMLInputElement>()

// 颜色数组，按索引循环分配不同颜色
const TAG_TYPES = ['', 'success', 'warning', 'danger', 'info', 'primary', 'success', 'warning']

function getTypeColor(index: number): string {
  return TAG_TYPES[index % TAG_TYPES.length]
}

async function loadSettings() {
  try {
    const data = await systemApi.getSettings()
    settings.check_interval = data.check_interval
    settings.scheduled_send_hour = data.scheduled_send_hour
    settings.scheduled_send_minute = data.scheduled_send_minute
    settings.categories = data.categories
    scheduledTime.value = `${String(data.scheduled_send_hour).padStart(2, '0')}:${String(data.scheduled_send_minute).padStart(2, '0')}`
  } catch (e) {
    console.error('加载设置失败', e)
  }
}

async function saveSettings() {
  saving.value = true
  try {
    const [hour, minute] = scheduledTime.value.split(':').map(Number)
    settings.scheduled_send_hour = hour
    settings.scheduled_send_minute = minute
    await systemApi.updateSettings({
      check_interval: settings.check_interval,
      scheduled_send_hour: hour,
      scheduled_send_minute: minute,
      categories: settings.categories
    })
    ElMessage.success('设置已保存')
    await loadJobs()
  } catch {
    ElMessage.error('保存失败')
  } finally {
    saving.value = false
  }
}

async function testConnection() {
  testing.value = true
  testResult.value = null
  try {
    const result = await systemApi.testConnection()
    testResult.value = { success: true, message: result.message || '连接成功' }
  } catch (e: any) {
    testResult.value = { success: false, message: e.detail || '连接失败' }
  } finally {
    testing.value = false
  }
}

async function handleSync() {
  syncing.value = true
  try {
    const result = await systemApi.triggerSync()
    if (result.success) {
      ElMessage.success(`同步成功: ${result.synced}封`)
    } else {
      ElMessage.error('同步失败')
    }
  } catch {
    ElMessage.error('同步失败')
  } finally {
    syncing.value = false
  }
}

async function handleParse() {
  parsing.value = true
  try {
    const result = await systemApi.triggerParse()
    ElMessage.success(`解析完成: ${result.processed}封`)
  } catch {
    ElMessage.error('解析失败')
  } finally {
    parsing.value = false
  }
}

async function sendSummary() {
  sending.value = true
  try {
    await systemApi.sendDailySummary()
    ElMessage.success('发送成功')
  } catch {
    ElMessage.error('发送失败')
  } finally {
    sending.value = false
  }
}

async function loadJobs() {
  jobsLoading.value = true
  try {
    jobs.value = await systemApi.getJobs()
  } catch {
    jobs.value = []
  } finally {
    jobsLoading.value = false
  }
}

function removeCategory(cat: string) {
  settings.categories = settings.categories.filter(c => c !== cat)
}

function showInput() {
  inputVisible.value = true
  nextTick(() => {
    inputRef.value?.focus()
  })
}

function handleInputConfirm() {
  if (inputValue.value) {
    settings.categories.push(inputValue.value)
  }
  inputVisible.value = false
  inputValue.value = ''
}

onMounted(() => {
  loadSettings()
  loadJobs()
})
</script>

<style scoped>
.settings-page {
  padding: 24px;
}

.header {
  margin-bottom: 24px;
}

.header h1 {
  font-size: 24px;
  font-weight: 600;
}

.settings-card {
  margin-bottom: 20px;
}

.card-header {
  font-size: 16px;
  font-weight: 600;
}

.mt-20 {
  margin-top: 20px;
}

.form-tip {
  margin-left: 8px;
  color: #909399;
  font-size: 14px;
}

.categories {
  display: flex;
  flex-wrap: wrap;
  gap: 8px;
}

.input-new-tag {
  width: 100px;
}
</style>
